% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name bone
%  @associatedFile /MATLAB Drive/bone cancer detetion1.m
%  @mostRecentlyActioned true
%  @uniqueId 45824B8D

bone cancer detetion1

%% @name anisodiff
%  @associatedFile /MATLAB Drive/anisodiff.m
%  @mostRecentlyActioned true
%  @uniqueId A3787418

anisodiff

